### PR TITLE
Dismiss picker on view disappearing

### PR DESCRIPTION
**Pull request by mammuth**
This fixes the following issue(s): 
#124

### CODE REVIEW

**Comment by mammuth** [comment]
When using this approach, the target-view isn't positioned properly anymore. Any guess why @mathiasquintero ?

Is there maybe a simpler solution than adding this to every VC?

image

**Comment by TG908** [comment]
I fixed it for you hope that is ok. I no longer allow the user to tap the back button when the slider is visible.

**Comment by TG908** [comment]
Damn it fixed hitting the back button but sliding on the edge of the view to go back still causes the glitch...

**Comment by mathiasquintero** [comment]
try disabling user interaction in the navigation controller

**Comment by mammuth** [comment]
Yep, `isUserInteractionEnabled` works 👍

**Comment by mammuth** [comment]
Argh, but the way I did it, of course also blocks clicking the back button or picker button...

**Comment by mammuth** [comment]
Now it should behave as intended I think 😊

**Comment by mammuth** [comment]
The picker is pretty duplicated in 5 VC's, maybe we get this in and make an issue for refactoring it sometime?

**Pull request merged**
