### PR TITLE
Add Continuous Integration

### LINKED ISSUE #52: Add Continuous Integration

### PR DESCRIPTION
**Pull request by mammuth**
Added Travis as a build server. Static Code analysis is sent to SonarQube. Some stuff will only work after this was merged into master (eg. linting new problems of PR's). Also, I will update the readme with information and instructions when the CI is up for this repo after the merge.

Closes #52

### CODE REVIEW

**Comment by kordianbruck** [comment]
Please make this a squash and merge when done. We don't need a merge commit here as the history is kinda messy. 

@mammuth you can also do this locally on your branch before opening the PR: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by mammuth** [comment]
Of course. We just squash it with the shiny new GitHub squash-before-merge-button.

**Comment by mammuth** [comment]
@mathiasquintero I also removed the old linked Pods_TUM_Campus_app.framework, and the second referenced group "TUM Campus App" in the last commit, since that led to errors after merging the master back into my branch. As far as I see, those are obsolete?
(That's also the reason why the Travis build failed).

I could imagine that I need some further fine-tuning when the merge is done.

**Comment by mammuth** [comment]
Just for the curious reader:
The build currently fails, because Travis is not exporting the set environment variables to the build machine: 

> "Travis CI makes encrypted variables and data available only to pull requests coming from the same repository. These are considered trustworthy, as only members with write access to the repository can send them."

https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions
Corresponding open issue: https://github.com/travis-ci/travis-ci/issues/1946

**Comment by mammuth** [comment]
I'm going to squash and merge. 

Since there are some changes to the project configuration etc, I checked out this branch into a new directory and tested whether it broke something for "normal" usage (building/running the app); it seems to work. However, if one of you @mathiasquintero or @TheZoker are faced with some issues due to my changes, just drop me a line!

**Pull request merged**
