### PR TITLE
Add refresh capabilities to calendar

### PR DESCRIPTION
**Pull request by mammuth**
@mathiasquintero could you please review this first draft? 😊 

I used a custom button because I thought this way it'll be easier to animate it. I'm not sure whether it's also easy doing it with a BarButton so we could use UIBarButtonSystemItem.refresh as an image.

**ToDo**

- [x] Use proper Icon
- [x] Signal update is in process, eg. by rotating the icon until the handler is called

This fixes the following issue(s): 
#158

### CODE REVIEW

**Comment by mathiasquintero** [comment]
I like the idea. Perhaps we should include that in my current refactoring. Since I want every module expect for search to be cached. Perhaps we just need a `byPassCache` option flag any managers fetch operation.

**Comment by mammuth** [comment]
You mean a bypass parameter in the fetchData method? Would be an optoin aswell 👍 
An extra updateData like I did may be more flexible.

**Comment by mammuth** [comment]
Now I'm replacing the refresh system icon with the system stop icon to indicate a refresh is in process. 

This PR is ready from my side now!
image

**Comment by mammuth** [comment]
I'd say let's get this in so we have it for 1.2 and change it afterwards based on @mathiasquintero refactorings in #167.

Wainting for review @mathiasquintero, @TG908 and others 😊

**Pull request merged**
