### PR TITLE
Fixed NavBar Glitch

### LINKED ISSUE #255: Wrong height of navigation bar
When opening the app, the navigation bar is displayed with a wrong height. It stays like this until you scroll the CollectionView.

simulator screen shot - iphone 7 plus - 2018-06-14 at 14 17 12

### PR DESCRIPTION
**Pull request by TG908**
This fixes #258 and fixes #255

### CODE REVIEW

**Comment by thellmund** [comment]
It this ready to be reviewed?

**Comment by TG908** [comment]
Yes

**Comment by thellmund** [comment]
The current implementation still has an odd behavior. This is what the nav bar looks like when launching the app, without any user interaction. 

simulator screen shot - iphone 7 - 2018-06-16 at 21 32 01

**Comment by TG908** [comment]
I patched it by just not displaying the loading animation on app launch (which btw no other app does so its fine).

**Comment by thellmund** [comment]
I don’t think we can make this comparison that easily. When launching, most apps get cached data from their on-device database and display it immediately. Simultaneously, they fetch the newest content from a remote source and display a network/loading indicator in the status bar. However, we currently don’t store data locally and always must fetch it from a remote source. Depending on the connection, this can take a while. 

Not showing any loading indicator might give the user the impression that the app is stuck. For that reason, I’m advocating for adding an indicator of some sort. If the refresh indicator causes glitches, we can think about adding a loading indicator in the center of the screen.

**Comment by thellmund** [comment]
Looking good to me now 👍

**Pull request merged**
