### PR TITLE
Refactoring a bit

### PR DESCRIPTION
**Pull request by mathiasquintero**
This code makes the data persistence of the log in a bit more straight forward by no longer storing two strings but rather a dictionary.

This also adds a dependency that I myself maintain: 'Sweeft' (Super proud of it)

I was also having some issues because of the spacing in the target name. Xcode 8.2 wasn't noticing the spaces and treated them as separate arguments on sh scripts.

### CODE REVIEW

**Comment by mammuth** [comment]
On this revision, no news images are shown in my simulator.

bildschirmfoto 2016-12-17 um 14 47 21

**Comment by mathiasquintero** [comment]
That's a strange bug. I'll check it out

**Comment by mammuth** [comment]
If it's something that doesn't occur for you, drop me a line then I try to investigate on my side aswell.

**Comment by mathiasquintero** [comment]
It is happening. I get no response from the server.

Try it: http://www.tu-film.de/img/film/poster/.thumb.How%20to%20Be%20Single.jpg

**Comment by mammuth** [comment]
Seems like their machine is down.

bildschirmfoto 2016-12-17 um 15 52 15

**Pull request merged**
