### PR TITLE
150 - Fix issue with user info not being updated correctly

### PR DESCRIPTION
**Pull request by rodalfus**
### Issue
When logging in, the user's name and data would not be updated correctly. The reason for this was that the token used to update the user's name was not forwarded to the `TUMDataManager`. This pull request fixes that in the following way: set the `TUMDataManager`'s user to be the shared (updated) user, add a fetch data method with a callback to `TUMDataManager`, thereby allowing the `MoreTableViewController` to update its data once the user is logged in.

This fixes the following issue(s): 
#150 

If there is no significant difference between the user object in `User.shared` and the user object in `TUMDataManager`, we could combine the two (with the added benefit, that the card view controller would work fine out of the box as well).

### CODE REVIEW

**Comment by rodalfus** [comment]
@mammuth Is that 👍 a yes to "let `TUMDataManager.user` be `User.shared`"? In how far does this need to change with @mathiasquintero's recent changes?

**Comment by mammuth** [comment]
> @mammuth Is that 👍 a yes to "let TUMDataManager.user be User.shared"?

It's just a "cool, thanks for the contribution!" 😉 

It's @mathiasquintero who is better suited for answering your second question.

**Comment by mathiasquintero** [comment]
@rodalfus  Sounds good to me. One singleton less ;)

**Comment by mathiasquintero** [comment]
@rodalfus can we get this one done so that it can go on the 1.2 Release

**Comment by rodalfus** [comment]
@mathiasquintero Sure.

**Comment by rodalfus** [comment]
@mathiasquintero Just to avoid confusion:

This is how I would go about this:

```
    var user: User? {
        return User.shared
    }
```
and remove the designated initialiser of `TUMDataManager`.

Do you have a better suggestion? Perhaps refactoring away `User.shared` is somewhat out-of-scope for a release this week (seems to be a pretty substantial change that requires extensive testing)?

**Comment by rodalfus** [comment]
I manually tested the changes in the following ways:
- Log in and out "above" the More screen -> Name was updated properly
- Log in and out "above" the Cards screen, switch to More screen -> Name was updated properly (after a short delay because of the network request)
- Log in and out "above" the Cards screen, refresh cards -> user specific cards are shown
- Test Calendar, My Lectures, Tuition Fees, Study Rooms, Cafeterias, News screens (could _not_ test some of the other screens since I don't have data for those or could not install the application on my device) -> all worked as expected.

From my side, this PR is ready.

**Pull request merged**
