### PR TITLE
Pinning Certificates

### LINKED ISSUE #234: Use app.tum.de
I will be making this domain the default. Please make sure you use it everywhere in the app.
Especially HTTPS pinning might be a problem.

### LINKED ISSUE #235: Use new email
app@tum.de

### LINKED ISSUE #243: Set a proper User Agent for API Calls
In Android we use the following:
> TCA Client 1.5.3/521  

Please update your useragent in all api requests to something more useful than:
>Campus/10 CFNetwork/894 Darwin/17.4.0  

We for sure need to know what version is connecting.

### PR DESCRIPTION
**Pull request by mathiasquintero**
### Issue
Fixes #234
Fixes #243
Fixes #235

### CODE REVIEW

**Comment by mathiasquintero** [comment]
@kordianbruck do we have the root ca sha256 fingerprint for the new host?

**Comment by kordianbruck** [comment]
@mathiasquintero which new host?

**Comment by mathiasquintero** [comment]
@kordianbruck is the Root CA for app.tum.de the same as for tumcabe.tum.de? Probably not, right?

**Comment by kordianbruck** [comment]
@mathiasquintero it even is the same certificate with just two SANs

**Comment by mathiasquintero** [comment]
@kordianbruck so as long as I pin the `DST Root CA X3` it should be fine, right?

**Comment by mathiasquintero** [comment]
Ah just saw it!
screen shot 2018-02-25 at 8 40 17 pm

**Comment by kordianbruck** [comment]
@mathiasquintero yea, pretty much

**Pull request merged**
