### PR TITLE
Tim/108-emailFeedback

### PR DESCRIPTION
**Pull request by TG908**
Added subject: [iOS] to support mail

### CODE REVIEW

**Comment by kordianbruck** [comment]
Can you also add the app version and ios version to the body please?

http://www.rapidtables.com/web/html/mailto.htm

**Comment by TG908** [comment]
How to you want it exactly: So far ive got
Subject: [iOS: 10.3.1, App Version 1.1]

**Comment by mammuth** [comment]
Nah, don't pack everything into the subject. You should be able to provide a text for the mail body as well 😉 Just keep [iOS] in the subject and add the versions to the mail body. 

It should be as easy as something like
_mailto:tca-support.os.in@tum.de?subject=[iOS]&body=iOS%20version:%20\(systemVersion),%20App%20Version:%20\(appVersion)_. 
At least on the web it is as easy 😛 

You probably need to urlencode it to remove whitespaces etc.

**Comment by TG908** [comment]
when i use mailto with a longer string the mail app will not open at all. Can but the version in the body though

**Comment by mathiasquintero** [comment]
@TG908 Check out `MailComposeController`

**Comment by TG908** [comment]
I am already using MFMailComposeViewController

**Pull request merged**
