### PR TITLE
Release/1.3

### LINKED ISSUE #72: Poor performance due to missing caching
So from what I've tested the app does not seem to cache most of the data. Most noticebly it happend several times that the app was unresponsive due to load some data (10-20 seconds in the case of the calendar).

We will run into problems with the TUM. Especially the calendar uses a lot of resources on their mainframe. That should be updated once every 7 days or so at the very most! (Ask @xsrf for more details on this)

Please take a look at the Androids caching mechanics: https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/main/java/de/tum/in/tumcampusapp/managers/CacheManager.java

### LINKED ISSUE #90: Refactor URLs
Refactor the creation of URLs by writing all the baseURLs in a JSON file . And finally get rid of all the warnings from Sonarqube

### LINKED ISSUE #109: Grades and Books should each be displayed in a single card
Todo: Create dedicated model for each of these cards

### LINKED ISSUE #118: More View crashes/doesnt display name
When the user is having a bad internet connection (try Network Link Conditioner edge for example) in the More Table View the users name is not loaded and clicking on the blank card is causing a crash.

```
var user: User? {
        didSet {
            updateView()
        }
    }
```

This code tries to update the view when the user is set. When the user is having a bad internet connection the user is set but `user.data` is not yet set. This will:

- cause a crash in the time `user.data` is not yet loaded on clicking the cell
- cause the name label to never be set since `updateViews()` is called when `user` is set not `user.data`

Related to #70 

I was able to fix the crash but the missing name is a bug in the model

### LINKED ISSUE #121: User Details don't always match the exact user
See Ticket #880490

So far we get the user details by a search with the exact name and filter the list a bit afaik. Perhaps tinker with the filtering a bit or try to fetch it from the LRZ id.

### LINKED ISSUE #156: Caching Everything
If individual room maps images aren't too large, we should consider caching them on device.

Obvious advantage of this is performance: if we don't have to load the images from the internet, we can display them way faster if the user is on a slow connection.

### LINKED ISSUE #179: Remove TabBar
As suggested by @TG908, the tabbar is kind of unneeded. 

Possible other ways to get to the more view:
- We could add the profile image to the toolbar which links to it
- some kind of swipe / dropdown similar to snapschat ( @mathiasquintero  idea)
- Your sexy idea here

### LINKED ISSUE #190: Large Titles?
What is your opinion on the large titles from iOS 11. Should we include them.

I think we should to keep our app's look as close as possible to other ios 11 apps. **With one exception: CardTableView** since we don't have a proper title for this vc (maybe someone of you guys knows a way to make the image move up like text).

### LINKED ISSUE #194: Let's do another release on Sunday
Planned Features (would close 11 issues and 4 PRs !):

- [x] #192 Remove Tab Bar
- [x] #167 network refactor
- [ ] #119 add default campus (needs work)

Anything else?

### LINKED ISSUE #195: Open every url in a SFSafariController
For the sake of consistency we should open all urls in a safari controller and not in safari itself.

I'd very much like this in the 1.3 aswell

### PR DESCRIPTION
**Pull request by TG908**
Please test this.

Fixes #190
Fixes #179
Fixes #118

Fixes #72
Fixes #109 
Starts progress in #43 & #165
Fixes #156
Fixes #90
Fixes #195
Fixes #194
Fixes #121

### CODE REVIEW

**Comment by mathiasquintero** [comment]
Since this branch has waaaay too much stuff here. I'd suggest we don't squash the commis this time in order to be able to separate them better in case something goes wrong.

And for the record in the future, we have to avoid MRs that span over more than one feature or bug...

**Comment by TG908** [comment]
@mathiasquintero I think for future releases we should make PRs for the release branch and after release if everything goes well we merge the release branch into master

**Comment by mathiasquintero** [comment]
@TG908 another idea would be to create a release branch. Always merge to master and cherry pick the features and bug fixes that will go to the release and merge those to the release branch

**Comment by TG908** [comment]
The library card is still missing. It also doesn't show up when clicking on edit.

**Comment by mathiasquintero** [comment]
@TG908 It is in edit. Under Book Rental

**Comment by TG908** [comment]
The card doesn't work on any of my devices

**Comment by mathiasquintero** [comment]
I understand. But I can't reproduce it without my account.

So you'll have to debug the functions where we fetch the rented books. I think we're failing to login

**Comment by TG908** [comment]
It also seems like Editing the card order or removing cards doesn't work

**Comment by mathiasquintero** [comment]
Fixed it

**Comment by mathiasquintero** [comment]
@TG908 Going to more and back makes the navbar in the card view have a large title. Even without text.

**Comment by mathiasquintero** [comment]
@TG908 is there anyway we can open the search results on the same navigation controller

**Comment by TG908** [comment]
@mathiasquintero I think the search results controller is opened in a whole new ui window

**Comment by mathiasquintero** [comment]
What if we keep a weak reference to the root vc and call push on those?

**Comment by TG908** [comment]
> @TG908 Going to more and back makes the navbar in the card view have a large title. Even without text.

I cannot reproduce this

> What if we keep a weak reference to the root vc and call push on those?
I'll try

**Comment by mathiasquintero** [comment]
Here you go! The text may not be there, but do you see the height difference?

simulator screen shot - iphone x - 2017-10-27 at 01 06 54
simulator screen shot - iphone x - 2017-10-27 at 01 06 58
simulator screen shot - iphone x - 2017-10-27 at 01 07 03

**Comment by TG908** [comment]
@mathiasquintero is this the iphone x?

**Comment by mathiasquintero** [comment]
Yes. But can be reproduced on any iphone

**Comment by TG908** [comment]
> What if we keep a weak reference to the root vc and call push on those?
 
Would work will do a proper implementation tomorrow.

**Comment by mathiasquintero** [comment]
@TG908 looks great now! I think we're done with most of what we wanted to do here. I'd say we are only missing the extra cards you wanted to make for like MVV, Library, Lectures, etc... 😉 

Perhaps you can get started on that in a separate branch starting from this one and we can later merge it back. So that we still follow the process

**Comment by TG908** [comment]
@mathiasquintero I think the new cards and improved ui might take a while, because I'm quite busy. What I still need to do is take a look at the BookRental Card. Otherwise we are good. 😄

**Comment by TG908** [comment]
Fixed Book Rentals we are ready for launch 🚀

**Comment by TG908** [comment]
Ready for take of

**Comment by mathiasquintero** [comment]
@mammuth have you checked this out?

**Comment by mathiasquintero** [comment]
We also have to update the bundle version

**Comment by mathiasquintero** [comment]
The build got stuck on `CalendarViewController.swift`. Dafuq?!?!

**Comment by mathiasquintero** [comment]
Merging this now!

**Pull request merged**
