### PR TITLE
Update pods dependencies to latest

### PR DESCRIPTION
**Pull request by TheZoker**

### CODE REVIEW

**Comment by mathiasquintero** [comment]
I don't see any changes in our code. I think there might be a problem with SwiftyJSON.JSON and Sweeft.JSON having the same name and being imported in the same file.

Does it build?

**Comment by TheZoker** [comment]
Yea it build on my end without any issues

**Comment by mathiasquintero** [comment]
BTW. You're welcome to help out on Sweeft ;) https://github.com/mathiasquintero/Sweeft

**Comment by TheZoker** [comment]
I will have a look at it, but since I'm not a swift expert and still trying to learn it, I'm not sure, if I could be helpful here.

**Pull request merged**
