### PR TITLE
Implement card ordering

### PR DESCRIPTION
**Pull request by thellmund**
This commit implement card ordering. Cards in `CardViewController`are now ordered as specified in `EditCardsViewController`.

### CODE REVIEW

**Comment by TG908** [comment]
I liked the old code better ... `var cardKeys: [CardKey] { return PersistentCardOrder.value.cards }`

**Comment by thellmund** [comment]
I'll have a look at the sorting extension 👍 

As this is work in progress, I planned on adding some caching mechanism for sortedDataSources before submitting it for review

**Comment by thellmund** [comment]
@TG908 I’ve just updated the branch with the sorting extension that you posted above as well as with caching. Let me know how you think it can be improved.

**Comment by TG908** [comment]
It would be simple to have sortedDataSources and allDataSources as instance variables, so you can get rid of the duplicate variable and the optional. You can then just set the filtered and sorted dataSources in init() and refresh()

**Pull request merged**
