### PR TITLE
Implemented error view and network timeout

### PR DESCRIPTION
**Pull request by TG908**
We now display an error message after trying for 10 seconds to load the cards.

simulator screen shot - iphone 8 plus - 2018-06-17 at 03 12 30

Some of the logic depends on #260

### CODE REVIEW

**Comment by thellmund** [comment]
I think the placeholder text should be less technical, along the lines of “Something went wrong”. Additionally, it should provide the user with an option to try again.

**Comment by TG908** [comment]
Updated version:
simulator screen shot - iphone 8 plus - 2018-06-21 at 01 07 56

**Comment by thellmund** [comment]
I like the design. Two questions: 
1. The header text size looks a little too big. Could you try something like Title 2?
2. What’s the rationale behind using a stack view with empty views to center the try again button? Can you try achieving the same design without them?

**Comment by thellmund** [comment]
I like the design. Two questions:
1. The header text size looks a little too big. Could you try something like Title 2?
2. What’s the rationale behind using a stack view with empty views to center the try again button? Can you try achieving the same design without them?

**Comment by TG908** [comment]
I think the font size matches the one used by apple in the App Store quite well

img_2401

**Comment by TG908** [comment]
> What’s the rationale behind using a stack view with empty views to center the try again button? Can you try achieving the same design without them?

Its the easiest way to center the button. It's unnecessarily complicated to archive the same thing in another way.

**Comment by thellmund** [comment]
> Its the easiest way to center the button.
Centering it horizontally via a constraint should be a little cleaner, I think.

**Comment by thellmund** [comment]
> Centering it horizontally via a constraint should be a little cleaner, I think.

Oh, it within a StackView. Then it’s fine 👌

**Pull request merged**
